package com.jielin.message.po;

import java.io.Serializable;
import java.util.Date;

public class MsgPlatform implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_platform.id
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_platform.name
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_platform.platform_code
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    private Integer platformCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_platform.enable
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    private Boolean enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_platform.create_time
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_platform.update_time
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jl_msg_platform
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_platform.id
     *
     * @return the value of jl_msg_platform.id
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_platform
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    public MsgPlatform withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_platform.id
     *
     * @param id the value for jl_msg_platform.id
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_platform.name
     *
     * @return the value of jl_msg_platform.name
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_platform
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    public MsgPlatform withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_platform.name
     *
     * @param name the value for jl_msg_platform.name
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_platform.platform_code
     *
     * @return the value of jl_msg_platform.platform_code
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    public Integer getPlatformCode() {
        return platformCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_platform
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    public MsgPlatform withPlatformCode(Integer platformCode) {
        this.setPlatformCode(platformCode);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_platform.platform_code
     *
     * @param platformCode the value for jl_msg_platform.platform_code
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    public void setPlatformCode(Integer platformCode) {
        this.platformCode = platformCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_platform.enable
     *
     * @return the value of jl_msg_platform.enable
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_platform
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    public MsgPlatform withEnable(Boolean enable) {
        this.setEnable(enable);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_platform.enable
     *
     * @param enable the value for jl_msg_platform.enable
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_platform.create_time
     *
     * @return the value of jl_msg_platform.create_time
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_platform
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    public MsgPlatform withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_platform.create_time
     *
     * @param createTime the value for jl_msg_platform.create_time
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_platform.update_time
     *
     * @return the value of jl_msg_platform.update_time
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_platform
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    public MsgPlatform withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_platform.update_time
     *
     * @param updateTime the value for jl_msg_platform.update_time
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_platform
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MsgPlatform other = (MsgPlatform) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getPlatformCode() == null ? other.getPlatformCode() == null : this.getPlatformCode().equals(other.getPlatformCode()))
            && (this.getEnable() == null ? other.getEnable() == null : this.getEnable().equals(other.getEnable()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_platform
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getPlatformCode() == null) ? 0 : getPlatformCode().hashCode());
        result = prime * result + ((getEnable() == null) ? 0 : getEnable().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_platform
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", platformCode=").append(platformCode);
        sb.append(", enable=").append(enable);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}