package com.jielin.message.po;

import java.io.Serializable;

public class MsgSendResultPo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_send_result.id
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_send_result.correlation_id
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    private String correlationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_send_result.message_id
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    private String messageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_send_result.result
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    private Integer result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_send_result.content
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jl_msg_send_result
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_send_result.id
     *
     * @return the value of jl_msg_send_result.id
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_send_result
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    public MsgSendResultPo withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_send_result.id
     *
     * @param id the value for jl_msg_send_result.id
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_send_result.correlation_id
     *
     * @return the value of jl_msg_send_result.correlation_id
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    public String getCorrelationId() {
        return correlationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_send_result
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    public MsgSendResultPo withCorrelationId(String correlationId) {
        this.setCorrelationId(correlationId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_send_result.correlation_id
     *
     * @param correlationId the value for jl_msg_send_result.correlation_id
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    public void setCorrelationId(String correlationId) {
        this.correlationId = correlationId == null ? null : correlationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_send_result.message_id
     *
     * @return the value of jl_msg_send_result.message_id
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_send_result
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    public MsgSendResultPo withMessageId(String messageId) {
        this.setMessageId(messageId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_send_result.message_id
     *
     * @param messageId the value for jl_msg_send_result.message_id
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    public void setMessageId(String messageId) {
        this.messageId = messageId == null ? null : messageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_send_result.result
     *
     * @return the value of jl_msg_send_result.result
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    public Integer getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_send_result
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    public MsgSendResultPo withResult(Integer result) {
        this.setResult(result);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_send_result.result
     *
     * @param result the value for jl_msg_send_result.result
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    public void setResult(Integer result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_send_result.content
     *
     * @return the value of jl_msg_send_result.content
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_send_result
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    public MsgSendResultPo withContent(String content) {
        this.setContent(content);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_send_result.content
     *
     * @param content the value for jl_msg_send_result.content
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_send_result
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MsgSendResultPo other = (MsgSendResultPo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCorrelationId() == null ? other.getCorrelationId() == null : this.getCorrelationId().equals(other.getCorrelationId()))
            && (this.getMessageId() == null ? other.getMessageId() == null : this.getMessageId().equals(other.getMessageId()))
            && (this.getResult() == null ? other.getResult() == null : this.getResult().equals(other.getResult()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_send_result
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCorrelationId() == null) ? 0 : getCorrelationId().hashCode());
        result = prime * result + ((getMessageId() == null) ? 0 : getMessageId().hashCode());
        result = prime * result + ((getResult() == null) ? 0 : getResult().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_send_result
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", correlationId=").append(correlationId);
        sb.append(", messageId=").append(messageId);
        sb.append(", result=").append(result);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}