package com.jielin.message.po;

import java.io.Serializable;
import java.util.Date;

public class MsgSendResultPo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_send_result.id
     *
     * @mbg.generated Mon Mar 09 17:22:10 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_send_result.correlation_id
     *
     * @mbg.generated Mon Mar 09 17:22:10 CST 2020
     */
    private String correlationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_send_result.result
     *
     * @mbg.generated Mon Mar 09 17:22:10 CST 2020
     */
    private Integer result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_send_result.fail_num
     *
     * @mbg.generated Mon Mar 09 17:22:10 CST 2020
     */
    private Integer failNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_send_result.update_time
     *
     * @mbg.generated Mon Mar 09 17:22:10 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_send_result.content
     *
     * @mbg.generated Mon Mar 09 17:22:10 CST 2020
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jl_msg_send_result
     *
     * @mbg.generated Mon Mar 09 17:22:10 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_send_result.id
     *
     * @return the value of jl_msg_send_result.id
     *
     * @mbg.generated Mon Mar 09 17:22:10 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_send_result
     *
     * @mbg.generated Mon Mar 09 17:22:10 CST 2020
     */
    public MsgSendResultPo withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_send_result.id
     *
     * @param id the value for jl_msg_send_result.id
     *
     * @mbg.generated Mon Mar 09 17:22:10 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_send_result.correlation_id
     *
     * @return the value of jl_msg_send_result.correlation_id
     *
     * @mbg.generated Mon Mar 09 17:22:10 CST 2020
     */
    public String getCorrelationId() {
        return correlationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_send_result
     *
     * @mbg.generated Mon Mar 09 17:22:10 CST 2020
     */
    public MsgSendResultPo withCorrelationId(String correlationId) {
        this.setCorrelationId(correlationId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_send_result.correlation_id
     *
     * @param correlationId the value for jl_msg_send_result.correlation_id
     *
     * @mbg.generated Mon Mar 09 17:22:10 CST 2020
     */
    public void setCorrelationId(String correlationId) {
        this.correlationId = correlationId == null ? null : correlationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_send_result.result
     *
     * @return the value of jl_msg_send_result.result
     *
     * @mbg.generated Mon Mar 09 17:22:10 CST 2020
     */
    public Integer getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_send_result
     *
     * @mbg.generated Mon Mar 09 17:22:10 CST 2020
     */
    public MsgSendResultPo withResult(Integer result) {
        this.setResult(result);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_send_result.result
     *
     * @param result the value for jl_msg_send_result.result
     *
     * @mbg.generated Mon Mar 09 17:22:10 CST 2020
     */
    public void setResult(Integer result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_send_result.fail_num
     *
     * @return the value of jl_msg_send_result.fail_num
     *
     * @mbg.generated Mon Mar 09 17:22:10 CST 2020
     */
    public Integer getFailNum() {
        return failNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_send_result
     *
     * @mbg.generated Mon Mar 09 17:22:10 CST 2020
     */
    public MsgSendResultPo withFailNum(Integer failNum) {
        this.setFailNum(failNum);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_send_result.fail_num
     *
     * @param failNum the value for jl_msg_send_result.fail_num
     *
     * @mbg.generated Mon Mar 09 17:22:10 CST 2020
     */
    public void setFailNum(Integer failNum) {
        this.failNum = failNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_send_result.update_time
     *
     * @return the value of jl_msg_send_result.update_time
     *
     * @mbg.generated Mon Mar 09 17:22:10 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_send_result
     *
     * @mbg.generated Mon Mar 09 17:22:10 CST 2020
     */
    public MsgSendResultPo withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_send_result.update_time
     *
     * @param updateTime the value for jl_msg_send_result.update_time
     *
     * @mbg.generated Mon Mar 09 17:22:10 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_send_result.content
     *
     * @return the value of jl_msg_send_result.content
     *
     * @mbg.generated Mon Mar 09 17:22:10 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_send_result
     *
     * @mbg.generated Mon Mar 09 17:22:10 CST 2020
     */
    public MsgSendResultPo withContent(String content) {
        this.setContent(content);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_send_result.content
     *
     * @param content the value for jl_msg_send_result.content
     *
     * @mbg.generated Mon Mar 09 17:22:10 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_send_result
     *
     * @mbg.generated Mon Mar 09 17:22:10 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MsgSendResultPo other = (MsgSendResultPo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCorrelationId() == null ? other.getCorrelationId() == null : this.getCorrelationId().equals(other.getCorrelationId()))
            && (this.getResult() == null ? other.getResult() == null : this.getResult().equals(other.getResult()))
            && (this.getFailNum() == null ? other.getFailNum() == null : this.getFailNum().equals(other.getFailNum()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_send_result
     *
     * @mbg.generated Mon Mar 09 17:22:10 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCorrelationId() == null) ? 0 : getCorrelationId().hashCode());
        result = prime * result + ((getResult() == null) ? 0 : getResult().hashCode());
        result = prime * result + ((getFailNum() == null) ? 0 : getFailNum().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_send_result
     *
     * @mbg.generated Mon Mar 09 17:22:10 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", correlationId=").append(correlationId);
        sb.append(", result=").append(result);
        sb.append(", failNum=").append(failNum);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}