package com.jielin.message.po;

import java.io.Serializable;

public class MsgThirdPo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_third.id
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_third.platform
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    private Integer platform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_third.user_type
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    private String userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_third.push_type
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    private Integer pushType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_third.url
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_third.http_method
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    private String httpMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jl_msg_third
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_third.id
     *
     * @return the value of jl_msg_third.id
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_third
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    public MsgThirdPo withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_third.id
     *
     * @param id the value for jl_msg_third.id
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_third.platform
     *
     * @return the value of jl_msg_third.platform
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    public Integer getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_third
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    public MsgThirdPo withPlatform(Integer platform) {
        this.setPlatform(platform);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_third.platform
     *
     * @param platform the value for jl_msg_third.platform
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    public void setPlatform(Integer platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_third.user_type
     *
     * @return the value of jl_msg_third.user_type
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_third
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    public MsgThirdPo withUserType(String userType) {
        this.setUserType(userType);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_third.user_type
     *
     * @param userType the value for jl_msg_third.user_type
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_third.push_type
     *
     * @return the value of jl_msg_third.push_type
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    public Integer getPushType() {
        return pushType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_third
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    public MsgThirdPo withPushType(Integer pushType) {
        this.setPushType(pushType);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_third.push_type
     *
     * @param pushType the value for jl_msg_third.push_type
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    public void setPushType(Integer pushType) {
        this.pushType = pushType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_third.url
     *
     * @return the value of jl_msg_third.url
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_third
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    public MsgThirdPo withUrl(String url) {
        this.setUrl(url);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_third.url
     *
     * @param url the value for jl_msg_third.url
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_third.http_method
     *
     * @return the value of jl_msg_third.http_method
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    public String getHttpMethod() {
        return httpMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_third
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    public MsgThirdPo withHttpMethod(String httpMethod) {
        this.setHttpMethod(httpMethod);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_third.http_method
     *
     * @param httpMethod the value for jl_msg_third.http_method
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    public void setHttpMethod(String httpMethod) {
        this.httpMethod = httpMethod == null ? null : httpMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_third
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MsgThirdPo other = (MsgThirdPo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPlatform() == null ? other.getPlatform() == null : this.getPlatform().equals(other.getPlatform()))
            && (this.getUserType() == null ? other.getUserType() == null : this.getUserType().equals(other.getUserType()))
            && (this.getPushType() == null ? other.getPushType() == null : this.getPushType().equals(other.getPushType()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getHttpMethod() == null ? other.getHttpMethod() == null : this.getHttpMethod().equals(other.getHttpMethod()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_third
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPlatform() == null) ? 0 : getPlatform().hashCode());
        result = prime * result + ((getUserType() == null) ? 0 : getUserType().hashCode());
        result = prime * result + ((getPushType() == null) ? 0 : getPushType().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getHttpMethod() == null) ? 0 : getHttpMethod().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_third
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", platform=").append(platform);
        sb.append(", userType=").append(userType);
        sb.append(", pushType=").append(pushType);
        sb.append(", url=").append(url);
        sb.append(", httpMethod=").append(httpMethod);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}