package com.jielin.message.po;

import java.io.Serializable;
import java.util.Date;

public class MsgUserPo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_user.id
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_user.platform
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    private Integer platform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_user.user_type
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    private String userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_user.user_id
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_user.user_phone
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    private String userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_user.uniapp_alias
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    private String uniappAlias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_user.wx_mp_openid
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    private String wxMpOpenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_user.wx_gzh_openid
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    private String wxGzhOpenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_user.create_time
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_user.update_time
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_user.id
     *
     * @return the value of jl_msg_user.id
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public MsgUserPo withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_user.id
     *
     * @param id the value for jl_msg_user.id
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_user.platform
     *
     * @return the value of jl_msg_user.platform
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public Integer getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public MsgUserPo withPlatform(Integer platform) {
        this.setPlatform(platform);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_user.platform
     *
     * @param platform the value for jl_msg_user.platform
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public void setPlatform(Integer platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_user.user_type
     *
     * @return the value of jl_msg_user.user_type
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public MsgUserPo withUserType(String userType) {
        this.setUserType(userType);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_user.user_type
     *
     * @param userType the value for jl_msg_user.user_type
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_user.user_id
     *
     * @return the value of jl_msg_user.user_id
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public MsgUserPo withUserId(Integer userId) {
        this.setUserId(userId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_user.user_id
     *
     * @param userId the value for jl_msg_user.user_id
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_user.user_phone
     *
     * @return the value of jl_msg_user.user_phone
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public MsgUserPo withUserPhone(String userPhone) {
        this.setUserPhone(userPhone);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_user.user_phone
     *
     * @param userPhone the value for jl_msg_user.user_phone
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_user.uniapp_alias
     *
     * @return the value of jl_msg_user.uniapp_alias
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public String getUniappAlias() {
        return uniappAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public MsgUserPo withUniappAlias(String uniappAlias) {
        this.setUniappAlias(uniappAlias);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_user.uniapp_alias
     *
     * @param uniappAlias the value for jl_msg_user.uniapp_alias
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public void setUniappAlias(String uniappAlias) {
        this.uniappAlias = uniappAlias == null ? null : uniappAlias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_user.wx_mp_openid
     *
     * @return the value of jl_msg_user.wx_mp_openid
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public String getWxMpOpenid() {
        return wxMpOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public MsgUserPo withWxMpOpenid(String wxMpOpenid) {
        this.setWxMpOpenid(wxMpOpenid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_user.wx_mp_openid
     *
     * @param wxMpOpenid the value for jl_msg_user.wx_mp_openid
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public void setWxMpOpenid(String wxMpOpenid) {
        this.wxMpOpenid = wxMpOpenid == null ? null : wxMpOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_user.wx_gzh_openid
     *
     * @return the value of jl_msg_user.wx_gzh_openid
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public String getWxGzhOpenid() {
        return wxGzhOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public MsgUserPo withWxGzhOpenid(String wxGzhOpenid) {
        this.setWxGzhOpenid(wxGzhOpenid);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_user.wx_gzh_openid
     *
     * @param wxGzhOpenid the value for jl_msg_user.wx_gzh_openid
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public void setWxGzhOpenid(String wxGzhOpenid) {
        this.wxGzhOpenid = wxGzhOpenid == null ? null : wxGzhOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_user.create_time
     *
     * @return the value of jl_msg_user.create_time
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public MsgUserPo withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_user.create_time
     *
     * @param createTime the value for jl_msg_user.create_time
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_user.update_time
     *
     * @return the value of jl_msg_user.update_time
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public MsgUserPo withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_user.update_time
     *
     * @param updateTime the value for jl_msg_user.update_time
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MsgUserPo other = (MsgUserPo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPlatform() == null ? other.getPlatform() == null : this.getPlatform().equals(other.getPlatform()))
            && (this.getUserType() == null ? other.getUserType() == null : this.getUserType().equals(other.getUserType()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUserPhone() == null ? other.getUserPhone() == null : this.getUserPhone().equals(other.getUserPhone()))
            && (this.getUniappAlias() == null ? other.getUniappAlias() == null : this.getUniappAlias().equals(other.getUniappAlias()))
            && (this.getWxMpOpenid() == null ? other.getWxMpOpenid() == null : this.getWxMpOpenid().equals(other.getWxMpOpenid()))
            && (this.getWxGzhOpenid() == null ? other.getWxGzhOpenid() == null : this.getWxGzhOpenid().equals(other.getWxGzhOpenid()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPlatform() == null) ? 0 : getPlatform().hashCode());
        result = prime * result + ((getUserType() == null) ? 0 : getUserType().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserPhone() == null) ? 0 : getUserPhone().hashCode());
        result = prime * result + ((getUniappAlias() == null) ? 0 : getUniappAlias().hashCode());
        result = prime * result + ((getWxMpOpenid() == null) ? 0 : getWxMpOpenid().hashCode());
        result = prime * result + ((getWxGzhOpenid() == null) ? 0 : getWxGzhOpenid().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", platform=").append(platform);
        sb.append(", userType=").append(userType);
        sb.append(", userId=").append(userId);
        sb.append(", userPhone=").append(userPhone);
        sb.append(", uniappAlias=").append(uniappAlias);
        sb.append(", wxMpOpenid=").append(wxMpOpenid);
        sb.append(", wxGzhOpenid=").append(wxGzhOpenid);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}