package com.jielin.message.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MsgUserPoCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public MsgUserPoCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPlatformIsNull() {
            addCriterion("platform is null");
            return (Criteria) this;
        }

        public Criteria andPlatformIsNotNull() {
            addCriterion("platform is not null");
            return (Criteria) this;
        }

        public Criteria andPlatformEqualTo(Integer value) {
            addCriterion("platform =", value, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformNotEqualTo(Integer value) {
            addCriterion("platform <>", value, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformGreaterThan(Integer value) {
            addCriterion("platform >", value, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformGreaterThanOrEqualTo(Integer value) {
            addCriterion("platform >=", value, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformLessThan(Integer value) {
            addCriterion("platform <", value, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformLessThanOrEqualTo(Integer value) {
            addCriterion("platform <=", value, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformIn(List<Integer> values) {
            addCriterion("platform in", values, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformNotIn(List<Integer> values) {
            addCriterion("platform not in", values, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformBetween(Integer value1, Integer value2) {
            addCriterion("platform between", value1, value2, "platform");
            return (Criteria) this;
        }

        public Criteria andPlatformNotBetween(Integer value1, Integer value2) {
            addCriterion("platform not between", value1, value2, "platform");
            return (Criteria) this;
        }

        public Criteria andUserTypeIsNull() {
            addCriterion("user_type is null");
            return (Criteria) this;
        }

        public Criteria andUserTypeIsNotNull() {
            addCriterion("user_type is not null");
            return (Criteria) this;
        }

        public Criteria andUserTypeEqualTo(String value) {
            addCriterion("user_type =", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotEqualTo(String value) {
            addCriterion("user_type <>", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeGreaterThan(String value) {
            addCriterion("user_type >", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeGreaterThanOrEqualTo(String value) {
            addCriterion("user_type >=", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLessThan(String value) {
            addCriterion("user_type <", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLessThanOrEqualTo(String value) {
            addCriterion("user_type <=", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLike(String value) {
            addCriterion("user_type like", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotLike(String value) {
            addCriterion("user_type not like", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeIn(List<String> values) {
            addCriterion("user_type in", values, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotIn(List<String> values) {
            addCriterion("user_type not in", values, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeBetween(String value1, String value2) {
            addCriterion("user_type between", value1, value2, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotBetween(String value1, String value2) {
            addCriterion("user_type not between", value1, value2, "userType");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserPhoneIsNull() {
            addCriterion("user_phone is null");
            return (Criteria) this;
        }

        public Criteria andUserPhoneIsNotNull() {
            addCriterion("user_phone is not null");
            return (Criteria) this;
        }

        public Criteria andUserPhoneEqualTo(String value) {
            addCriterion("user_phone =", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNotEqualTo(String value) {
            addCriterion("user_phone <>", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneGreaterThan(String value) {
            addCriterion("user_phone >", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("user_phone >=", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneLessThan(String value) {
            addCriterion("user_phone <", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneLessThanOrEqualTo(String value) {
            addCriterion("user_phone <=", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneLike(String value) {
            addCriterion("user_phone like", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNotLike(String value) {
            addCriterion("user_phone not like", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneIn(List<String> values) {
            addCriterion("user_phone in", values, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNotIn(List<String> values) {
            addCriterion("user_phone not in", values, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneBetween(String value1, String value2) {
            addCriterion("user_phone between", value1, value2, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNotBetween(String value1, String value2) {
            addCriterion("user_phone not between", value1, value2, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUniappAliasIsNull() {
            addCriterion("uniapp_alias is null");
            return (Criteria) this;
        }

        public Criteria andUniappAliasIsNotNull() {
            addCriterion("uniapp_alias is not null");
            return (Criteria) this;
        }

        public Criteria andUniappAliasEqualTo(String value) {
            addCriterion("uniapp_alias =", value, "uniappAlias");
            return (Criteria) this;
        }

        public Criteria andUniappAliasNotEqualTo(String value) {
            addCriterion("uniapp_alias <>", value, "uniappAlias");
            return (Criteria) this;
        }

        public Criteria andUniappAliasGreaterThan(String value) {
            addCriterion("uniapp_alias >", value, "uniappAlias");
            return (Criteria) this;
        }

        public Criteria andUniappAliasGreaterThanOrEqualTo(String value) {
            addCriterion("uniapp_alias >=", value, "uniappAlias");
            return (Criteria) this;
        }

        public Criteria andUniappAliasLessThan(String value) {
            addCriterion("uniapp_alias <", value, "uniappAlias");
            return (Criteria) this;
        }

        public Criteria andUniappAliasLessThanOrEqualTo(String value) {
            addCriterion("uniapp_alias <=", value, "uniappAlias");
            return (Criteria) this;
        }

        public Criteria andUniappAliasLike(String value) {
            addCriterion("uniapp_alias like", value, "uniappAlias");
            return (Criteria) this;
        }

        public Criteria andUniappAliasNotLike(String value) {
            addCriterion("uniapp_alias not like", value, "uniappAlias");
            return (Criteria) this;
        }

        public Criteria andUniappAliasIn(List<String> values) {
            addCriterion("uniapp_alias in", values, "uniappAlias");
            return (Criteria) this;
        }

        public Criteria andUniappAliasNotIn(List<String> values) {
            addCriterion("uniapp_alias not in", values, "uniappAlias");
            return (Criteria) this;
        }

        public Criteria andUniappAliasBetween(String value1, String value2) {
            addCriterion("uniapp_alias between", value1, value2, "uniappAlias");
            return (Criteria) this;
        }

        public Criteria andUniappAliasNotBetween(String value1, String value2) {
            addCriterion("uniapp_alias not between", value1, value2, "uniappAlias");
            return (Criteria) this;
        }

        public Criteria andWxMpOpenidIsNull() {
            addCriterion("wx_mp_openid is null");
            return (Criteria) this;
        }

        public Criteria andWxMpOpenidIsNotNull() {
            addCriterion("wx_mp_openid is not null");
            return (Criteria) this;
        }

        public Criteria andWxMpOpenidEqualTo(String value) {
            addCriterion("wx_mp_openid =", value, "wxMpOpenid");
            return (Criteria) this;
        }

        public Criteria andWxMpOpenidNotEqualTo(String value) {
            addCriterion("wx_mp_openid <>", value, "wxMpOpenid");
            return (Criteria) this;
        }

        public Criteria andWxMpOpenidGreaterThan(String value) {
            addCriterion("wx_mp_openid >", value, "wxMpOpenid");
            return (Criteria) this;
        }

        public Criteria andWxMpOpenidGreaterThanOrEqualTo(String value) {
            addCriterion("wx_mp_openid >=", value, "wxMpOpenid");
            return (Criteria) this;
        }

        public Criteria andWxMpOpenidLessThan(String value) {
            addCriterion("wx_mp_openid <", value, "wxMpOpenid");
            return (Criteria) this;
        }

        public Criteria andWxMpOpenidLessThanOrEqualTo(String value) {
            addCriterion("wx_mp_openid <=", value, "wxMpOpenid");
            return (Criteria) this;
        }

        public Criteria andWxMpOpenidLike(String value) {
            addCriterion("wx_mp_openid like", value, "wxMpOpenid");
            return (Criteria) this;
        }

        public Criteria andWxMpOpenidNotLike(String value) {
            addCriterion("wx_mp_openid not like", value, "wxMpOpenid");
            return (Criteria) this;
        }

        public Criteria andWxMpOpenidIn(List<String> values) {
            addCriterion("wx_mp_openid in", values, "wxMpOpenid");
            return (Criteria) this;
        }

        public Criteria andWxMpOpenidNotIn(List<String> values) {
            addCriterion("wx_mp_openid not in", values, "wxMpOpenid");
            return (Criteria) this;
        }

        public Criteria andWxMpOpenidBetween(String value1, String value2) {
            addCriterion("wx_mp_openid between", value1, value2, "wxMpOpenid");
            return (Criteria) this;
        }

        public Criteria andWxMpOpenidNotBetween(String value1, String value2) {
            addCriterion("wx_mp_openid not between", value1, value2, "wxMpOpenid");
            return (Criteria) this;
        }

        public Criteria andWxGzhOpenidIsNull() {
            addCriterion("wx_gzh_openid is null");
            return (Criteria) this;
        }

        public Criteria andWxGzhOpenidIsNotNull() {
            addCriterion("wx_gzh_openid is not null");
            return (Criteria) this;
        }

        public Criteria andWxGzhOpenidEqualTo(String value) {
            addCriterion("wx_gzh_openid =", value, "wxGzhOpenid");
            return (Criteria) this;
        }

        public Criteria andWxGzhOpenidNotEqualTo(String value) {
            addCriterion("wx_gzh_openid <>", value, "wxGzhOpenid");
            return (Criteria) this;
        }

        public Criteria andWxGzhOpenidGreaterThan(String value) {
            addCriterion("wx_gzh_openid >", value, "wxGzhOpenid");
            return (Criteria) this;
        }

        public Criteria andWxGzhOpenidGreaterThanOrEqualTo(String value) {
            addCriterion("wx_gzh_openid >=", value, "wxGzhOpenid");
            return (Criteria) this;
        }

        public Criteria andWxGzhOpenidLessThan(String value) {
            addCriterion("wx_gzh_openid <", value, "wxGzhOpenid");
            return (Criteria) this;
        }

        public Criteria andWxGzhOpenidLessThanOrEqualTo(String value) {
            addCriterion("wx_gzh_openid <=", value, "wxGzhOpenid");
            return (Criteria) this;
        }

        public Criteria andWxGzhOpenidLike(String value) {
            addCriterion("wx_gzh_openid like", value, "wxGzhOpenid");
            return (Criteria) this;
        }

        public Criteria andWxGzhOpenidNotLike(String value) {
            addCriterion("wx_gzh_openid not like", value, "wxGzhOpenid");
            return (Criteria) this;
        }

        public Criteria andWxGzhOpenidIn(List<String> values) {
            addCriterion("wx_gzh_openid in", values, "wxGzhOpenid");
            return (Criteria) this;
        }

        public Criteria andWxGzhOpenidNotIn(List<String> values) {
            addCriterion("wx_gzh_openid not in", values, "wxGzhOpenid");
            return (Criteria) this;
        }

        public Criteria andWxGzhOpenidBetween(String value1, String value2) {
            addCriterion("wx_gzh_openid between", value1, value2, "wxGzhOpenid");
            return (Criteria) this;
        }

        public Criteria andWxGzhOpenidNotBetween(String value1, String value2) {
            addCriterion("wx_gzh_openid not between", value1, value2, "wxGzhOpenid");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jl_msg_user
     *
     * @mbg.generated do_not_delete_during_merge Tue Jan 07 11:35:20 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}