package com.jielin.message.po;

import java.io.Serializable;
import java.util.Date;

public class OperatePo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_operate.id
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_operate.operate_name
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    private String operateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_operate.operate_type
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    private Byte operateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_operate.create_time
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_operate.update_time
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_operate.enable
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    private Boolean enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_operate.push_all
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    private Boolean pushAll;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jl_msg_operate
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_operate.id
     *
     * @return the value of jl_msg_operate.id
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_operate
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    public OperatePo withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_operate.id
     *
     * @param id the value for jl_msg_operate.id
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_operate.operate_name
     *
     * @return the value of jl_msg_operate.operate_name
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    public String getOperateName() {
        return operateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_operate
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    public OperatePo withOperateName(String operateName) {
        this.setOperateName(operateName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_operate.operate_name
     *
     * @param operateName the value for jl_msg_operate.operate_name
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    public void setOperateName(String operateName) {
        this.operateName = operateName == null ? null : operateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_operate.operate_type
     *
     * @return the value of jl_msg_operate.operate_type
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    public Byte getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_operate
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    public OperatePo withOperateType(Byte operateType) {
        this.setOperateType(operateType);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_operate.operate_type
     *
     * @param operateType the value for jl_msg_operate.operate_type
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    public void setOperateType(Byte operateType) {
        this.operateType = operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_operate.create_time
     *
     * @return the value of jl_msg_operate.create_time
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_operate
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    public OperatePo withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_operate.create_time
     *
     * @param createTime the value for jl_msg_operate.create_time
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_operate.update_time
     *
     * @return the value of jl_msg_operate.update_time
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_operate
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    public OperatePo withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_operate.update_time
     *
     * @param updateTime the value for jl_msg_operate.update_time
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_operate.enable
     *
     * @return the value of jl_msg_operate.enable
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_operate
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    public OperatePo withEnable(Boolean enable) {
        this.setEnable(enable);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_operate.enable
     *
     * @param enable the value for jl_msg_operate.enable
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_operate.push_all
     *
     * @return the value of jl_msg_operate.push_all
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    public Boolean getPushAll() {
        return pushAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_operate
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    public OperatePo withPushAll(Boolean pushAll) {
        this.setPushAll(pushAll);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_operate.push_all
     *
     * @param pushAll the value for jl_msg_operate.push_all
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    public void setPushAll(Boolean pushAll) {
        this.pushAll = pushAll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_operate
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OperatePo other = (OperatePo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOperateName() == null ? other.getOperateName() == null : this.getOperateName().equals(other.getOperateName()))
            && (this.getOperateType() == null ? other.getOperateType() == null : this.getOperateType().equals(other.getOperateType()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getEnable() == null ? other.getEnable() == null : this.getEnable().equals(other.getEnable()))
            && (this.getPushAll() == null ? other.getPushAll() == null : this.getPushAll().equals(other.getPushAll()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_operate
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOperateName() == null) ? 0 : getOperateName().hashCode());
        result = prime * result + ((getOperateType() == null) ? 0 : getOperateType().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getEnable() == null) ? 0 : getEnable().hashCode());
        result = prime * result + ((getPushAll() == null) ? 0 : getPushAll().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_operate
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", operateName=").append(operateName);
        sb.append(", operateType=").append(operateType);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", enable=").append(enable);
        sb.append(", pushAll=").append(pushAll);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}