package com.jielin.message.po;

import java.io.Serializable;
import java.util.Date;

public class OptionPo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_option.id
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_option.push_name
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    private String pushName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_option.push_type
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    private Byte pushType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_option.create_time
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_option.update_time
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_option.enable
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    private Boolean enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jl_msg_option
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_option.id
     *
     * @return the value of jl_msg_option.id
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_option
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    public OptionPo withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_option.id
     *
     * @param id the value for jl_msg_option.id
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_option.push_name
     *
     * @return the value of jl_msg_option.push_name
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    public String getPushName() {
        return pushName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_option
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    public OptionPo withPushName(String pushName) {
        this.setPushName(pushName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_option.push_name
     *
     * @param pushName the value for jl_msg_option.push_name
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    public void setPushName(String pushName) {
        this.pushName = pushName == null ? null : pushName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_option.push_type
     *
     * @return the value of jl_msg_option.push_type
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    public Byte getPushType() {
        return pushType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_option
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    public OptionPo withPushType(Byte pushType) {
        this.setPushType(pushType);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_option.push_type
     *
     * @param pushType the value for jl_msg_option.push_type
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    public void setPushType(Byte pushType) {
        this.pushType = pushType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_option.create_time
     *
     * @return the value of jl_msg_option.create_time
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_option
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    public OptionPo withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_option.create_time
     *
     * @param createTime the value for jl_msg_option.create_time
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_option.update_time
     *
     * @return the value of jl_msg_option.update_time
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_option
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    public OptionPo withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_option.update_time
     *
     * @param updateTime the value for jl_msg_option.update_time
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_option.enable
     *
     * @return the value of jl_msg_option.enable
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_option
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    public OptionPo withEnable(Boolean enable) {
        this.setEnable(enable);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_option.enable
     *
     * @param enable the value for jl_msg_option.enable
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_option
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OptionPo other = (OptionPo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPushName() == null ? other.getPushName() == null : this.getPushName().equals(other.getPushName()))
            && (this.getPushType() == null ? other.getPushType() == null : this.getPushType().equals(other.getPushType()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getEnable() == null ? other.getEnable() == null : this.getEnable().equals(other.getEnable()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_option
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPushName() == null) ? 0 : getPushName().hashCode());
        result = prime * result + ((getPushType() == null) ? 0 : getPushType().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getEnable() == null) ? 0 : getEnable().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_option
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", pushName=").append(pushName);
        sb.append(", pushType=").append(pushType);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", enable=").append(enable);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}