package com.jielin.message.po;

import java.io.Serializable;
import java.util.Date;

public class UniappPo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_uniapp.id
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_uniapp.app_type
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    private String appType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_uniapp.app_id
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_uniapp.app_secret
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    private String appSecret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_uniapp.app_key
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    private String appKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_uniapp.master_secret
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    private String masterSecret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_uniapp.enable
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    private Boolean enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_uniapp.create_time
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_uniapp.update_time
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_uniapp.platform
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    private Byte platform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jl_msg_uniapp.application_id
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    private String applicationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jl_msg_uniapp
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_uniapp.id
     *
     * @return the value of jl_msg_uniapp.id
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_uniapp
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public UniappPo withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_uniapp.id
     *
     * @param id the value for jl_msg_uniapp.id
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_uniapp.app_type
     *
     * @return the value of jl_msg_uniapp.app_type
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public String getAppType() {
        return appType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_uniapp
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public UniappPo withAppType(String appType) {
        this.setAppType(appType);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_uniapp.app_type
     *
     * @param appType the value for jl_msg_uniapp.app_type
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public void setAppType(String appType) {
        this.appType = appType == null ? null : appType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_uniapp.app_id
     *
     * @return the value of jl_msg_uniapp.app_id
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_uniapp
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public UniappPo withAppId(String appId) {
        this.setAppId(appId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_uniapp.app_id
     *
     * @param appId the value for jl_msg_uniapp.app_id
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_uniapp.app_secret
     *
     * @return the value of jl_msg_uniapp.app_secret
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public String getAppSecret() {
        return appSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_uniapp
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public UniappPo withAppSecret(String appSecret) {
        this.setAppSecret(appSecret);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_uniapp.app_secret
     *
     * @param appSecret the value for jl_msg_uniapp.app_secret
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public void setAppSecret(String appSecret) {
        this.appSecret = appSecret == null ? null : appSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_uniapp.app_key
     *
     * @return the value of jl_msg_uniapp.app_key
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_uniapp
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public UniappPo withAppKey(String appKey) {
        this.setAppKey(appKey);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_uniapp.app_key
     *
     * @param appKey the value for jl_msg_uniapp.app_key
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey == null ? null : appKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_uniapp.master_secret
     *
     * @return the value of jl_msg_uniapp.master_secret
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public String getMasterSecret() {
        return masterSecret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_uniapp
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public UniappPo withMasterSecret(String masterSecret) {
        this.setMasterSecret(masterSecret);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_uniapp.master_secret
     *
     * @param masterSecret the value for jl_msg_uniapp.master_secret
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public void setMasterSecret(String masterSecret) {
        this.masterSecret = masterSecret == null ? null : masterSecret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_uniapp.enable
     *
     * @return the value of jl_msg_uniapp.enable
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_uniapp
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public UniappPo withEnable(Boolean enable) {
        this.setEnable(enable);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_uniapp.enable
     *
     * @param enable the value for jl_msg_uniapp.enable
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_uniapp.create_time
     *
     * @return the value of jl_msg_uniapp.create_time
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_uniapp
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public UniappPo withCreateTime(Date createTime) {
        this.setCreateTime(createTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_uniapp.create_time
     *
     * @param createTime the value for jl_msg_uniapp.create_time
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_uniapp.update_time
     *
     * @return the value of jl_msg_uniapp.update_time
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_uniapp
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public UniappPo withUpdateTime(Date updateTime) {
        this.setUpdateTime(updateTime);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_uniapp.update_time
     *
     * @param updateTime the value for jl_msg_uniapp.update_time
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_uniapp.platform
     *
     * @return the value of jl_msg_uniapp.platform
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public Byte getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_uniapp
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public UniappPo withPlatform(Byte platform) {
        this.setPlatform(platform);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_uniapp.platform
     *
     * @param platform the value for jl_msg_uniapp.platform
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public void setPlatform(Byte platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jl_msg_uniapp.application_id
     *
     * @return the value of jl_msg_uniapp.application_id
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public String getApplicationId() {
        return applicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_uniapp
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public UniappPo withApplicationId(String applicationId) {
        this.setApplicationId(applicationId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jl_msg_uniapp.application_id
     *
     * @param applicationId the value for jl_msg_uniapp.application_id
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    public void setApplicationId(String applicationId) {
        this.applicationId = applicationId == null ? null : applicationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_uniapp
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UniappPo other = (UniappPo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAppType() == null ? other.getAppType() == null : this.getAppType().equals(other.getAppType()))
            && (this.getAppId() == null ? other.getAppId() == null : this.getAppId().equals(other.getAppId()))
            && (this.getAppSecret() == null ? other.getAppSecret() == null : this.getAppSecret().equals(other.getAppSecret()))
            && (this.getAppKey() == null ? other.getAppKey() == null : this.getAppKey().equals(other.getAppKey()))
            && (this.getMasterSecret() == null ? other.getMasterSecret() == null : this.getMasterSecret().equals(other.getMasterSecret()))
            && (this.getEnable() == null ? other.getEnable() == null : this.getEnable().equals(other.getEnable()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getPlatform() == null ? other.getPlatform() == null : this.getPlatform().equals(other.getPlatform()))
            && (this.getApplicationId() == null ? other.getApplicationId() == null : this.getApplicationId().equals(other.getApplicationId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_uniapp
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAppType() == null) ? 0 : getAppType().hashCode());
        result = prime * result + ((getAppId() == null) ? 0 : getAppId().hashCode());
        result = prime * result + ((getAppSecret() == null) ? 0 : getAppSecret().hashCode());
        result = prime * result + ((getAppKey() == null) ? 0 : getAppKey().hashCode());
        result = prime * result + ((getMasterSecret() == null) ? 0 : getMasterSecret().hashCode());
        result = prime * result + ((getEnable() == null) ? 0 : getEnable().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getPlatform() == null) ? 0 : getPlatform().hashCode());
        result = prime * result + ((getApplicationId() == null) ? 0 : getApplicationId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_uniapp
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", appType=").append(appType);
        sb.append(", appId=").append(appId);
        sb.append(", appSecret=").append(appSecret);
        sb.append(", appKey=").append(appKey);
        sb.append(", masterSecret=").append(masterSecret);
        sb.append(", enable=").append(enable);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", platform=").append(platform);
        sb.append(", applicationId=").append(applicationId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}