package com.jielin.message.dao.mysql;

import com.jielin.message.po.GtAliasPo;
import org.apache.ibatis.annotations.Param;
import org.springframework.cache.annotation.CacheConfig;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
@CacheConfig(cacheNames = "GtAlias")
public interface GtAliasDao {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_gt_alias
     *
     * @mbg.generated Tue Oct 08 17:19:36 CST 2019
     */
    int insert(GtAliasPo record);

    List<GtAliasPo> selectByCid(@Param("cid") String cid);

    @Cacheable(key = "#root.methodName+':'+#appType+':'+#phone")
    String selectAliasByPhone(@Param("appType") String appType, @Param("phone") String phone);
}