package com.jielin.message.dao.mysql;

import com.jielin.message.po.MsgPlatform;
import com.jielin.message.po.MsgPlatformCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface MsgPlatformDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_platform
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    long countByExample(MsgPlatformCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_platform
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    int deleteByExample(MsgPlatformCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_platform
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    int insert(MsgPlatform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_platform
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    int insertSelective(MsgPlatform record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_platform
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    List<MsgPlatform> selectByExampleWithRowbounds(MsgPlatformCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_platform
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    List<MsgPlatform> selectByExample(MsgPlatformCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_platform
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") MsgPlatform record, @Param("example") MsgPlatformCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_platform
     *
     * @mbg.generated Fri Jan 03 15:51:38 CST 2020
     */
    int updateByExample(@Param("record") MsgPlatform record, @Param("example") MsgPlatformCriteria example);
}