package com.jielin.message.dao.mysql;

import com.jielin.message.po.MsgSendResultPo;
import com.jielin.message.po.MsgSendResultPoCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface MsgSendResultDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_send_result
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    long countByExample(MsgSendResultPoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_send_result
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    int deleteByExample(MsgSendResultPoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_send_result
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    int insert(MsgSendResultPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_send_result
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    int insertSelective(MsgSendResultPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_send_result
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    List<MsgSendResultPo> selectByExampleWithBLOBsWithRowbounds(MsgSendResultPoCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_send_result
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    List<MsgSendResultPo> selectByExampleWithBLOBs(MsgSendResultPoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_send_result
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    List<MsgSendResultPo> selectByExampleWithRowbounds(MsgSendResultPoCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_send_result
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    List<MsgSendResultPo> selectByExample(MsgSendResultPoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_send_result
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    int updateByExampleSelective(@Param("record") MsgSendResultPo record, @Param("example") MsgSendResultPoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_send_result
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") MsgSendResultPo record, @Param("example") MsgSendResultPoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_send_result
     *
     * @mbg.generated Fri Feb 28 13:17:56 CST 2020
     */
    int updateByExample(@Param("record") MsgSendResultPo record, @Param("example") MsgSendResultPoCriteria example);

    int updateStatus(@Param("status") Integer status, @Param("correlationId") String correlationId);
}