package com.jielin.message.dao.mysql;

import com.jielin.message.po.MsgThirdPo;
import com.jielin.message.po.MsgThirdPoCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface MsgThirdDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_third
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    long countByExample(MsgThirdPoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_third
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    int deleteByExample(MsgThirdPoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_third
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    int insert(MsgThirdPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_third
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    int insertSelective(MsgThirdPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_third
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    List<MsgThirdPo> selectByExampleWithRowbounds(MsgThirdPoCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_third
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    List<MsgThirdPo> selectByExample(MsgThirdPoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_third
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    int updateByExampleSelective(@Param("record") MsgThirdPo record, @Param("example") MsgThirdPoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_third
     *
     * @mbg.generated Tue Jan 07 10:11:35 CST 2020
     */
    int updateByExample(@Param("record") MsgThirdPo record, @Param("example") MsgThirdPoCriteria example);
}