package com.jielin.message.dao.mysql;

import com.jielin.message.po.MsgUserPo;
import com.jielin.message.po.MsgUserPoCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.cache.annotation.CacheConfig;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
@CacheConfig(cacheNames = "MsgUser")
public interface MsgUserDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    long countByExample(MsgUserPoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    int deleteByExample(MsgUserPoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    int insert(MsgUserPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    int insertSelective(MsgUserPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    List<MsgUserPo> selectByExampleWithRowbounds(MsgUserPoCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    List<MsgUserPo> selectByExample(MsgUserPoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */
    @CacheEvict(allEntries = true)
    int updateByExampleSelective(@Param("record") MsgUserPo record, @Param("example") MsgUserPoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_user
     *
     * @mbg.generated Tue Jan 07 11:35:20 CST 2020
     */

    @CacheEvict(allEntries = true)
    int updateByExample(@Param("record") MsgUserPo record, @Param("example") MsgUserPoCriteria example);

    @Cacheable(key = "#root.methodName+':'+#platform+':'+#userType+':'+#userId")
    MsgUserPo selectByCondition(@Param("platform") Integer platform,
                                @Param("userType") String userType, @Param("userId") Integer userId);

}