package com.jielin.message.dao.mysql;

import com.jielin.message.po.OperatePo;
import com.jielin.message.po.OperatePoCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface OperateDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_operate
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    long countByExample(OperatePoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_operate
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    int deleteByExample(OperatePoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_operate
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    int insert(OperatePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_operate
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    int insertSelective(OperatePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_operate
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    List<OperatePo> selectByExampleWithRowbounds(OperatePoCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_operate
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    List<OperatePo> selectByExample(OperatePoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_operate
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") OperatePo record, @Param("example") OperatePoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_operate
     *
     * @mbg.generated Mon Nov 04 15:12:57 CST 2019
     */
    int updateByExample(@Param("record") OperatePo record, @Param("example") OperatePoCriteria example);
}