package com.jielin.message.dao.mysql;

import com.jielin.message.po.OptionPo;
import com.jielin.message.po.OptionPoCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface OptionDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_option
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    long countByExample(OptionPoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_option
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    int deleteByExample(OptionPoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_option
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    int insert(OptionPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_option
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    int insertSelective(OptionPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_option
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    List<OptionPo> selectByExampleWithRowbounds(OptionPoCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_option
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    List<OptionPo> selectByExample(OptionPoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_option
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    int updateByExampleSelective(@Param("record") OptionPo record, @Param("example") OptionPoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_option
     *
     * @mbg.generated Mon Oct 21 11:09:44 CST 2019
     */
    int updateByExample(@Param("record") OptionPo record, @Param("example") OptionPoCriteria example);
}