package com.jielin.message.dao.mysql;

import com.jielin.message.po.UniappPo;
import com.jielin.message.po.UniappPoCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.cache.annotation.CacheConfig;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
@CacheConfig(cacheNames = "uniappDao")
public interface UniappDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_uniapp
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    long countByExample(UniappPoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_uniapp
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    int deleteByExample(UniappPoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_uniapp
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    int insert(UniappPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_uniapp
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    int insertSelective(UniappPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_uniapp
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    List<UniappPo> selectByExampleWithRowbounds(UniappPoCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_uniapp
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    List<UniappPo> selectByExample(UniappPoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_uniapp
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    int updateByExampleSelective(@Param("record") UniappPo record, @Param("example") UniappPoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jl_msg_uniapp
     *
     * @mbg.generated Wed Aug 05 18:08:34 CST 2020
     */
    int updateByExample(@Param("record") UniappPo record, @Param("example") UniappPoCriteria example);
}